version: '3.8'

services:
  app: 
    container_name: chemo-task
    image: chemo-task
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000