version: '3.8'

services:
  chemo-task: 
    container_name: chemo-task
    image: chemo-task
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000